# Generated by Django 3.1 on 2020-08-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date_added', models.DateTimeField(verbose_name='Date Added')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieter.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_time', models.DateTimeField(verbose_name='Suggested Time')),
                ('time_served', models.DateTimeField(blank=True, null=True, verbose_name='Time Served')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieter.meal')),
            ],
        ),
    ]
